apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-config
data:
  config.json: |
    {
      "sampleKey": "sampleValue",
      "createdBy": "helm",
      "environment": "{{ .Values.springProfile }}"
    }
