apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-creds
  namespace: {{ .Release.Namespace }}
type: Opaque

{{- /* --- compute or reuse values --- */}}
{{- $secretName := printf "%s-creds" (include "spring-boot-api.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $username := randAlphaNum 24 | b64enc }}
{{- $password := randAlphaNum 40 | b64enc }}
{{- if $existing }}
{{- $username = (index $existing.data "USERNAME" | default $username) }}
{{- $password = (index $existing.data "PASSWORD" | default $password) }}
{{- end }}

data:
  USERNAME: {{ $username | quote }}
  PASSWORD: {{ $password | quote }}
