image:
  repository: busybox
  tag: stable
  pullPolicy: IfNotPresent

replicaCount: 1
springProfile: dev

service:
  type: ClusterIP

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: ""
  host: dev.example.com
